swagger: "2.0"
info:
  title: Sample API
  description: API test
  version: 1.0.0

host: mailhog.php.docker.localhost:8025
basePath: /
schemes:
  - http
  - https

paths:
  /:
    get:
      summary: Return email arrived
      description: Test Email
      consumes:
        - application/json
        - application/xml
        - application/yaml
      produces:
        - application/json
        - application/yaml
      responses:
        200:
          description: Your email has arrived! 