swagger: "2.0"
info:
  title: Sample API
  description: API test
  version: 1.0.0

host: mailhog.php.docker.localhost:8025
basePath: 
schemes:
  - http
  - https

paths:
  /api/v2/messages:
    get:
      summary: Return email arrived
      description: Test Email
      parameters:
      - in: query
        name: start
        description: start index
        required: false
        type: number
        format: int64
        default: 0
      - in: query
        name: limit
        description: Number of messages
        required: false
        type: number
        format: int64
        default: 50
      produces:
        - application/json
        - application/yaml
      responses:
        200:
          description: Your email has arrived! 